# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup GraalVM action
  # You may pin to the exact commit or the version.
  # uses: ayltai/setup-graalvm@cf54edea07234dcdf627020fe836f4a6cf548822
      uses: ayltai/setup-graalvm@v1
      with:
    # The JDK version to be installed with GraalVM. E.g. 8, 11. See https://github.com/graalvm/graalvm-ce-builds/releases
        java-version: 11
    # The version of GraalVM to make available on PATH. E.g. 20.1.0, 19.3.2. See https://github.com/graalvm/graalvm-ce-builds/releases
        graalvm-version: 11
    # Install GraalVM Native Image
        native-image: true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
